/**
 * gameTitles.ts — Liste complète de jeux vidéo pour l'autocomplete de PixelNight.
 * ~1 200 titres couvrant : PS1/2/3/4/5, Xbox/360/One, N64, GameCube, Wii, Switch,
 * NES, SNES, Game Boy/GBA/DS/3DS, PSP, Sega Genesis, Dreamcast, PC.
 *
 * Triés par série pour faciliter la maintenance.
 */

export const GAME_TITLES: string[] = [

  // ── Mario ────────────────────────────────────────────────────────────────────
  "Super Mario Bros",
  "Super Mario Bros: The Lost Levels",
  "Super Mario Bros 2",
  "Super Mario Bros 3",
  "Super Mario World",
  "Super Mario Land",
  "Super Mario Land 2: 6 Golden Coins",
  "Super Mario 64",
  "Super Mario Sunshine",
  "Super Mario Galaxy",
  "Super Mario Galaxy 2",
  "Super Mario 3D Land",
  "Super Mario 3D World",
  "Super Mario Odyssey",
  "Super Mario Bros Wonder",
  "New Super Mario Bros",
  "New Super Mario Bros Wii",
  "New Super Mario Bros 2",
  "New Super Mario Bros U",
  "Super Mario RPG",
  "Super Mario RPG: Legend of the Seven Stars",
  "Paper Mario",
  "Paper Mario: The Thousand-Year Door",
  "Paper Mario: The Origami King",
  "Paper Mario: Color Splash",
  "Paper Mario: Sticker Star",
  "Mario & Luigi: Superstar Saga",
  "Mario & Luigi: Partners in Time",
  "Mario & Luigi: Bowser's Inside Story",
  "Mario & Luigi: Dream Team",
  "Mario & Rabbids Kingdom Battle",
  "Mario & Rabbids Sparks of Hope",
  "Mario Kart 64",
  "Mario Kart: Double Dash!!",
  "Mario Kart Wii",
  "Mario Kart 7",
  "Mario Kart 8",
  "Mario Kart 8 Deluxe",
  "Mario Party",
  "Mario Party 2",
  "Mario Party 3",
  "Mario Party 4",
  "Mario Party 5",
  "Mario Party 6",
  "Mario Party 7",
  "Mario Party 8",
  "Mario Party 9",
  "Super Mario Party",
  "Mario Party Superstars",
  "Mario Party: The Top 100",
  "Mario Tennis",
  "Mario Tennis Aces",
  "Mario Tennis: Ultra Smash",
  "Mario Golf: Super Rush",
  "Mario Golf: Toadstool Tour",
  "Mario Strikers: Battle League",
  "Dr. Mario",
  "Dr. Mario World",
  "Captain Toad: Treasure Tracker",
  "Yoshi's Island",
  "Yoshi's Story",
  "Yoshi's Woolly World",
  "Yoshi's Crafted World",
  "Yoshi's New Island",
  "WarioWare: Get It Together!",
  "WarioWare: Move It!",
  "WarioWare Gold",
  "Wario Land: Shake It!",
  "Wario Land 4",

  // ── Zelda ────────────────────────────────────────────────────────────────────
  "The Legend of Zelda",
  "Zelda II: The Adventure of Link",
  "The Legend of Zelda: A Link to the Past",
  "The Legend of Zelda: Link's Awakening",
  "The Legend of Zelda: Ocarina of Time",
  "The Legend of Zelda: Majora's Mask",
  "The Legend of Zelda: Oracle of Ages",
  "The Legend of Zelda: Oracle of Seasons",
  "The Legend of Zelda: The Wind Waker",
  "The Legend of Zelda: The Minish Cap",
  "The Legend of Zelda: Twilight Princess",
  "The Legend of Zelda: Phantom Hourglass",
  "The Legend of Zelda: Spirit Tracks",
  "The Legend of Zelda: Skyward Sword",
  "The Legend of Zelda: A Link Between Worlds",
  "The Legend of Zelda: Tri Force Heroes",
  "The Legend of Zelda: Breath of the Wild",
  "The Legend of Zelda: Tears of the Kingdom",
  "Hyrule Warriors",
  "Hyrule Warriors: Age of Calamity",
  "The Legend of Zelda: Four Swords Adventures",
  "Cadence of Hyrule",

  // ── Pokémon ──────────────────────────────────────────────────────────────────
  "Pokemon Red",
  "Pokemon Blue",
  "Pokemon Yellow",
  "Pokemon Gold",
  "Pokemon Silver",
  "Pokemon Crystal",
  "Pokemon Ruby",
  "Pokemon Sapphire",
  "Pokemon Emerald",
  "Pokemon FireRed",
  "Pokemon LeafGreen",
  "Pokemon Diamond",
  "Pokemon Pearl",
  "Pokemon Platinum",
  "Pokemon HeartGold",
  "Pokemon SoulSilver",
  "Pokemon Black",
  "Pokemon White",
  "Pokemon Black 2",
  "Pokemon White 2",
  "Pokemon X",
  "Pokemon Y",
  "Pokemon Omega Ruby",
  "Pokemon Alpha Sapphire",
  "Pokemon Sun",
  "Pokemon Moon",
  "Pokemon Ultra Sun",
  "Pokemon Ultra Moon",
  "Pokemon Sword",
  "Pokemon Shield",
  "Pokemon Scarlet",
  "Pokemon Violet",
  "Pokemon Legends: Arceus",
  "Pokemon Go",
  "Pokemon Stadium",
  "Pokemon Stadium 2",
  "Pokemon Snap",
  "New Pokemon Snap",
  "Pokemon Unite",
  "Pokemon Mystery Dungeon: Red Rescue Team",
  "Pokemon Mystery Dungeon: Explorers of Time",
  "Pokemon Mystery Dungeon: Explorers of Sky",
  "Pokemon Colosseum",
  "Pokemon XD: Gale of Darkness",
  "Pokemon Ranger",
  "Pokken Tournament",

  // ── Sonic ────────────────────────────────────────────────────────────────────
  "Sonic the Hedgehog",
  "Sonic the Hedgehog 2",
  "Sonic the Hedgehog 3",
  "Sonic & Knuckles",
  "Sonic CD",
  "Sonic 3D Blast",
  "Sonic Spinball",
  "Sonic Adventure",
  "Sonic Adventure 2",
  "Sonic Heroes",
  "Shadow the Hedgehog",
  "Sonic the Hedgehog (2006)",
  "Sonic Unleashed",
  "Sonic and the Secret Rings",
  "Sonic and the Black Knight",
  "Sonic Colors",
  "Sonic Generations",
  "Sonic Lost World",
  "Sonic Mania",
  "Sonic Forces",
  "Sonic Frontiers",
  "Sonic Superstars",
  "Sonic Riders",
  "Sonic Riders: Zero Gravity",
  "Team Sonic Racing",
  "Sonic Rush",
  "Sonic Rush Adventure",
  "Sonic Chronicles: The Dark Brotherhood",

  // ── Final Fantasy ─────────────────────────────────────────────────────────────
  "Final Fantasy",
  "Final Fantasy II",
  "Final Fantasy III",
  "Final Fantasy IV",
  "Final Fantasy V",
  "Final Fantasy VI",
  "Final Fantasy VII",
  "Final Fantasy VII Remake",
  "Final Fantasy VII Rebirth",
  "Crisis Core: Final Fantasy VII",
  "Crisis Core: Final Fantasy VII Reunion",
  "Final Fantasy VIII",
  "Final Fantasy IX",
  "Final Fantasy X",
  "Final Fantasy X-2",
  "Final Fantasy XI",
  "Final Fantasy XII",
  "Final Fantasy XII: The Zodiac Age",
  "Final Fantasy XIII",
  "Final Fantasy XIII-2",
  "Lightning Returns: Final Fantasy XIII",
  "Final Fantasy XIV",
  "Final Fantasy XIV: Endwalker",
  "Final Fantasy XIV: Shadowbringers",
  "Final Fantasy XV",
  "Final Fantasy XVI",
  "Final Fantasy Tactics",
  "Final Fantasy Tactics Advance",
  "Final Fantasy Crystal Chronicles",
  "Stranger of Paradise: Final Fantasy Origin",
  "Final Fantasy Type-0",
  "Dissidia Final Fantasy",

  // ── Dragon Quest ─────────────────────────────────────────────────────────────
  "Dragon Quest",
  "Dragon Quest II",
  "Dragon Quest III",
  "Dragon Quest IV",
  "Dragon Quest V",
  "Dragon Quest VI",
  "Dragon Quest VII",
  "Dragon Quest VIII",
  "Dragon Quest IX",
  "Dragon Quest X",
  "Dragon Quest XI",
  "Dragon Quest XI S: Echoes of an Elusive Age",
  "Dragon Quest Builders",
  "Dragon Quest Builders 2",
  "Dragon Quest Heroes",
  "Dragon Quest Heroes 2",
  "Dragon Quest Monsters",

  // ── Monster Hunter ───────────────────────────────────────────────────────────
  "Monster Hunter",
  "Monster Hunter Freedom",
  "Monster Hunter Freedom 2",
  "Monster Hunter Freedom Unite",
  "Monster Hunter Tri",
  "Monster Hunter 3 Ultimate",
  "Monster Hunter 4",
  "Monster Hunter 4 Ultimate",
  "Monster Hunter Generations",
  "Monster Hunter Generations Ultimate",
  "Monster Hunter: World",
  "Monster Hunter World: Iceborne",
  "Monster Hunter Rise",
  "Monster Hunter Rise: Sunbreak",
  "Monster Hunter Wilds",
  "Monster Hunter Stories",
  "Monster Hunter Stories 2: Wings of Ruin",

  // ── Call of Duty ─────────────────────────────────────────────────────────────
  "Call of Duty",
  "Call of Duty 2",
  "Call of Duty 3",
  "Call of Duty 4: Modern Warfare",
  "Call of Duty: World at War",
  "Call of Duty: Modern Warfare 2",
  "Call of Duty: Black Ops",
  "Call of Duty: Modern Warfare 3",
  "Call of Duty: Black Ops 2",
  "Call of Duty: Ghosts",
  "Call of Duty: Advanced Warfare",
  "Call of Duty: Black Ops 3",
  "Call of Duty: Infinite Warfare",
  "Call of Duty: WWII",
  "Call of Duty: Black Ops 4",
  "Call of Duty: Modern Warfare (2019)",
  "Call of Duty: Black Ops Cold War",
  "Call of Duty: Vanguard",
  "Call of Duty: Modern Warfare 2 (2022)",
  "Call of Duty: Modern Warfare 3 (2023)",
  "Call of Duty: Warzone",

  // ── Resident Evil ─────────────────────────────────────────────────────────────
  "Resident Evil",
  "Resident Evil 2",
  "Resident Evil 3: Nemesis",
  "Resident Evil 4",
  "Resident Evil 5",
  "Resident Evil 6",
  "Resident Evil 7: Biohazard",
  "Resident Evil Village",
  "Resident Evil 2 Remake",
  "Resident Evil 3 Remake",
  "Resident Evil 4 Remake",
  "Resident Evil: Code Veronica",
  "Resident Evil Zero",
  "Resident Evil Revelations",
  "Resident Evil Revelations 2",

  // ── God of War ────────────────────────────────────────────────────────────────
  "God of War",
  "God of War II",
  "God of War III",
  "God of War: Ascension",
  "God of War: Ghost of Sparta",
  "God of War: Chains of Olympus",
  "God of War (2018)",
  "God of War Ragnarök",

  // ── Halo ──────────────────────────────────────────────────────────────────────
  "Halo: Combat Evolved",
  "Halo 2",
  "Halo 3",
  "Halo 3: ODST",
  "Halo: Reach",
  "Halo 4",
  "Halo 5: Guardians",
  "Halo Infinite",
  "Halo Wars",
  "Halo Wars 2",

  // ── Metal Gear ────────────────────────────────────────────────────────────────
  "Metal Gear",
  "Metal Gear 2: Solid Snake",
  "Metal Gear Solid",
  "Metal Gear Solid 2: Sons of Liberty",
  "Metal Gear Solid 3: Snake Eater",
  "Metal Gear Solid 4: Guns of the Patriots",
  "Metal Gear Solid: Peace Walker",
  "Metal Gear Solid V: Ground Zeroes",
  "Metal Gear Solid V: The Phantom Pain",
  "Metal Gear Rising: Revengeance",
  "Metal Gear Survive",

  // ── Castlevania ───────────────────────────────────────────────────────────────
  "Castlevania",
  "Castlevania II: Simon's Quest",
  "Castlevania III: Dracula's Curse",
  "Super Castlevania IV",
  "Castlevania: Rondo of Blood",
  "Castlevania: Symphony of the Night",
  "Castlevania 64",
  "Castlevania: Circle of the Moon",
  "Castlevania: Harmony of Dissonance",
  "Castlevania: Aria of Sorrow",
  "Castlevania: Dawn of Sorrow",
  "Castlevania: Portrait of Ruin",
  "Castlevania: Order of Ecclesia",
  "Castlevania: Lords of Shadow",
  "Castlevania: Lords of Shadow 2",
  "Castlevania: Curse of Darkness",

  // ── Mega Man ──────────────────────────────────────────────────────────────────
  "Mega Man",
  "Mega Man 2",
  "Mega Man 3",
  "Mega Man 4",
  "Mega Man 5",
  "Mega Man 6",
  "Mega Man 7",
  "Mega Man 8",
  "Mega Man 9",
  "Mega Man 10",
  "Mega Man 11",
  "Mega Man X",
  "Mega Man X2",
  "Mega Man X3",
  "Mega Man X4",
  "Mega Man X5",
  "Mega Man X6",
  "Mega Man X7",
  "Mega Man X8",
  "Mega Man Zero",
  "Mega Man Zero 2",
  "Mega Man Zero 3",
  "Mega Man Zero 4",
  "Mega Man ZX",
  "Mega Man ZX Advent",
  "Mega Man Legends",
  "Mega Man Legends 2",
  "Mega Man Battle Network",
  "Mega Man Battle Network 2",
  "Mega Man Battle Network 3",
  "Mega Man Star Force",

  // ── Street Fighter ────────────────────────────────────────────────────────────
  "Street Fighter",
  "Street Fighter II",
  "Street Fighter II Turbo: Hyper Fighting",
  "Super Street Fighter II",
  "Street Fighter Alpha",
  "Street Fighter Alpha 2",
  "Street Fighter Alpha 3",
  "Street Fighter III: Third Strike",
  "Street Fighter IV",
  "Super Street Fighter IV",
  "Ultra Street Fighter IV",
  "Street Fighter V",
  "Street Fighter 6",
  "Street Fighter EX",

  // ── Mortal Kombat ─────────────────────────────────────────────────────────────
  "Mortal Kombat",
  "Mortal Kombat II",
  "Mortal Kombat 3",
  "Ultimate Mortal Kombat 3",
  "Mortal Kombat 4",
  "Mortal Kombat: Deadly Alliance",
  "Mortal Kombat: Deception",
  "Mortal Kombat: Armageddon",
  "Mortal Kombat vs DC Universe",
  "Mortal Kombat (2011)",
  "Mortal Kombat X",
  "Mortal Kombat 11",
  "Mortal Kombat 1 (2023)",

  // ── Tekken ────────────────────────────────────────────────────────────────────
  "Tekken",
  "Tekken 2",
  "Tekken 3",
  "Tekken 4",
  "Tekken 5",
  "Tekken 5: Dark Resurrection",
  "Tekken 6",
  "Tekken 7",
  "Tekken 8",
  "Tekken Tag Tournament",
  "Tekken Tag Tournament 2",

  // ── Dark Souls / FromSoftware ─────────────────────────────────────────────────
  "Demon's Souls",
  "Demon's Souls Remake",
  "Dark Souls",
  "Dark Souls II",
  "Dark Souls III",
  "Bloodborne",
  "Sekiro: Shadows Die Twice",
  "Elden Ring",
  "Armored Core VI: Fires of Rubicon",

  // ── The Elder Scrolls / Fallout ───────────────────────────────────────────────
  "The Elder Scrolls: Arena",
  "The Elder Scrolls II: Daggerfall",
  "The Elder Scrolls III: Morrowind",
  "The Elder Scrolls IV: Oblivion",
  "The Elder Scrolls V: Skyrim",
  "The Elder Scrolls Online",
  "Fallout",
  "Fallout 2",
  "Fallout 3",
  "Fallout: New Vegas",
  "Fallout 4",
  "Fallout 76",
  "Fallout Shelter",
  "Starfield",

  // ── The Witcher / CD Projekt ───────────────────────────────────────────────────
  "The Witcher",
  "The Witcher 2: Assassins of Kings",
  "The Witcher 3: Wild Hunt",
  "Cyberpunk 2077",
  "Cyberpunk 2077: Phantom Liberty",

  // ── GTA / Red Dead ────────────────────────────────────────────────────────────
  "Grand Theft Auto",
  "Grand Theft Auto 2",
  "Grand Theft Auto III",
  "Grand Theft Auto: Vice City",
  "Grand Theft Auto: San Andreas",
  "Grand Theft Auto: Liberty City Stories",
  "Grand Theft Auto: Vice City Stories",
  "Grand Theft Auto IV",
  "Grand Theft Auto V",
  "Grand Theft Auto: Chinatown Wars",
  "GTA Online",
  "Red Dead Revolver",
  "Red Dead Redemption",
  "Red Dead Redemption 2",

  // ── Assassin's Creed ──────────────────────────────────────────────────────────
  "Assassin's Creed",
  "Assassin's Creed 2",
  "Assassin's Creed Brotherhood",
  "Assassin's Creed Revelations",
  "Assassin's Creed 3",
  "Assassin's Creed 4: Black Flag",
  "Assassin's Creed Rogue",
  "Assassin's Creed Unity",
  "Assassin's Creed Syndicate",
  "Assassin's Creed Origins",
  "Assassin's Creed Odyssey",
  "Assassin's Creed Valhalla",
  "Assassin's Creed Mirage",
  "Assassin's Creed Shadows",

  // ── FIFA / Sports ─────────────────────────────────────────────────────────────
  "FIFA 98",
  "FIFA 99",
  "FIFA 2000",
  "FIFA 2001",
  "FIFA 2002",
  "FIFA 2003",
  "FIFA 2004",
  "FIFA 2005",
  "FIFA 06",
  "FIFA 07",
  "FIFA 08",
  "FIFA 09",
  "FIFA 10",
  "FIFA 11",
  "FIFA 12",
  "FIFA 13",
  "FIFA 14",
  "FIFA 15",
  "FIFA 16",
  "FIFA 17",
  "FIFA 18",
  "FIFA 19",
  "FIFA 20",
  "FIFA 21",
  "FIFA 22",
  "FIFA 23",
  "EA Sports FC 24",
  "EA Sports FC 25",
  "Pro Evolution Soccer 6",
  "eFootball 2024",
  "NBA 2K20",
  "NBA 2K21",
  "NBA 2K22",
  "NBA 2K23",
  "NBA 2K24",
  "NBA Jam",
  "NBA Street",
  "Madden NFL 25",
  "WWE 2K23",
  "UFC 5",
  "NHL 24",
  "F1 24",
  "F1 23",
  "WRC",
  "MotoGP 23",

  // ── Crash Bandicoot ───────────────────────────────────────────────────────────
  "Crash Bandicoot",
  "Crash Bandicoot 2: Cortex Strikes Back",
  "Crash Bandicoot: Warped",
  "Crash Bandicoot: The Wrath of Cortex",
  "Crash Twinsanity",
  "Crash of the Titans",
  "Crash Bandicoot 4: It's About Time",
  "Crash Team Racing",
  "Crash Team Racing Nitro-Fueled",
  "Crash Bash",

  // ── Spyro ─────────────────────────────────────────────────────────────────────
  "Spyro the Dragon",
  "Spyro 2: Ripto's Rage",
  "Spyro: Year of the Dragon",
  "Spyro: A Hero's Tail",
  "Spyro Reignited Trilogy",

  // ── Tomb Raider ───────────────────────────────────────────────────────────────
  "Tomb Raider",
  "Tomb Raider II",
  "Tomb Raider III",
  "Tomb Raider: The Last Revelation",
  "Tomb Raider: Chronicles",
  "Tomb Raider: Angel of Darkness",
  "Tomb Raider: Legend",
  "Tomb Raider: Anniversary",
  "Tomb Raider: Underworld",
  "Tomb Raider (2013)",
  "Rise of the Tomb Raider",
  "Shadow of the Tomb Raider",

  // ── Uncharted ─────────────────────────────────────────────────────────────────
  "Uncharted: Drake's Fortune",
  "Uncharted 2: Among Thieves",
  "Uncharted 3: Drake's Deception",
  "Uncharted 4: A Thief's End",
  "Uncharted: The Lost Legacy",
  "Uncharted: Golden Abyss",

  // ── The Last of Us ────────────────────────────────────────────────────────────
  "The Last of Us",
  "The Last of Us Part 2",
  "The Last of Us Part 1",

  // ── Spider-Man ────────────────────────────────────────────────────────────────
  "Marvel's Spider-Man",
  "Marvel's Spider-Man: Miles Morales",
  "Marvel's Spider-Man 2",

  // ── Batman Arkham ─────────────────────────────────────────────────────────────
  "Batman: Arkham Asylum",
  "Batman: Arkham City",
  "Batman: Arkham Origins",
  "Batman: Arkham Knight",

  // ── Borderlands ───────────────────────────────────────────────────────────────
  "Borderlands",
  "Borderlands 2",
  "Borderlands: The Pre-Sequel",
  "Borderlands 3",
  "Tales from the Borderlands",
  "Tiny Tina's Wonderlands",

  // ── BioShock ──────────────────────────────────────────────────────────────────
  "BioShock",
  "BioShock 2",
  "BioShock Infinite",

  // ── Mass Effect ───────────────────────────────────────────────────────────────
  "Mass Effect",
  "Mass Effect 2",
  "Mass Effect 3",
  "Mass Effect: Andromeda",
  "Mass Effect Legendary Edition",

  // ── Dragon Age ────────────────────────────────────────────────────────────────
  "Dragon Age: Origins",
  "Dragon Age 2",
  "Dragon Age: Inquisition",
  "Dragon Age: The Veilguard",

  // ── The Sims ──────────────────────────────────────────────────────────────────
  "The Sims",
  "The Sims 2",
  "The Sims 3",
  "The Sims 4",
  "SimCity",
  "SimCity 4",
  "Cities: Skylines",
  "Cities: Skylines 2",

  // ── Age of Empires / Civilization ─────────────────────────────────────────────
  "Age of Empires",
  "Age of Empires II",
  "Age of Empires III",
  "Age of Empires IV",
  "Age of Mythology",
  "Civilization",
  "Civilization II",
  "Civilization III",
  "Civilization IV",
  "Civilization V",
  "Civilization VI",
  "Civilization VII",
  "Sid Meier's Alpha Centauri",

  // ── Donkey Kong ───────────────────────────────────────────────────────────────
  "Donkey Kong",
  "Donkey Kong Country",
  "Donkey Kong Country 2: Diddy's Kong Quest",
  "Donkey Kong Country 3: Dixie Kong's Double Trouble!",
  "Donkey Kong 64",
  "Donkey Kong Country Returns",
  "Donkey Kong Country: Tropical Freeze",
  "Donkey Kong: Bananza",

  // ── Kirby ─────────────────────────────────────────────────────────────────────
  "Kirby's Dream Land",
  "Kirby's Adventure",
  "Kirby's Dream Land 2",
  "Kirby's Dream Land 3",
  "Kirby 64: The Crystal Shards",
  "Kirby: Nightmare in Dream Land",
  "Kirby Air Ride",
  "Kirby: Canvas Curse",
  "Kirby Super Star Ultra",
  "Kirby's Epic Yarn",
  "Kirby's Return to Dream Land",
  "Kirby: Triple Deluxe",
  "Kirby: Planet Robobot",
  "Kirby Star Allies",
  "Kirby and the Forgotten Land",

  // ── Metroid ───────────────────────────────────────────────────────────────────
  "Metroid",
  "Metroid II: Return of Samus",
  "Super Metroid",
  "Metroid Fusion",
  "Metroid: Zero Mission",
  "Metroid Prime",
  "Metroid Prime 2: Echoes",
  "Metroid Prime 3: Corruption",
  "Metroid: Other M",
  "Metroid: Samus Returns",
  "Metroid Dread",
  "Metroid Prime Remastered",
  "Metroid Prime 4: Beyond",

  // ── Star Fox ──────────────────────────────────────────────────────────────────
  "Star Fox",
  "Star Fox 64",
  "Star Fox Adventures",
  "Star Fox Assault",
  "Star Fox Command",
  "Star Fox Zero",
  "Star Fox 2",

  // ── F-Zero ────────────────────────────────────────────────────────────────────
  "F-Zero",
  "F-Zero X",
  "F-Zero GX",
  "F-Zero 99",

  // ── Pikmin ────────────────────────────────────────────────────────────────────
  "Pikmin",
  "Pikmin 2",
  "Pikmin 3",
  "Pikmin 4",
  "Hey! Pikmin",

  // ── Animal Crossing ───────────────────────────────────────────────────────────
  "Animal Crossing",
  "Animal Crossing: Wild World",
  "Animal Crossing: City Folk",
  "Animal Crossing: New Leaf",
  "Animal Crossing: New Horizons",
  "Animal Crossing: Happy Home Paradise",
  "Animal Crossing: Happy Home Designer",

  // ── Splatoon ──────────────────────────────────────────────────────────────────
  "Splatoon",
  "Splatoon 2",
  "Splatoon 3",

  // ── Fire Emblem ───────────────────────────────────────────────────────────────
  "Fire Emblem: Shadow Dragon",
  "Fire Emblem: The Blazing Blade",
  "Fire Emblem: The Sacred Stones",
  "Fire Emblem: Path of Radiance",
  "Fire Emblem: Radiant Dawn",
  "Fire Emblem Awakening",
  "Fire Emblem Fates",
  "Fire Emblem Echoes: Shadows of Valentia",
  "Fire Emblem: Three Houses",
  "Fire Emblem Engage",
  "Fire Emblem Warriors",
  "Fire Emblem Warriors: Three Hopes",

  // ── Xenoblade ─────────────────────────────────────────────────────────────────
  "Xenoblade Chronicles",
  "Xenoblade Chronicles 2",
  "Xenoblade Chronicles 3",
  "Xenoblade Chronicles: Definitive Edition",
  "Xenoblade Chronicles X",
  "Xenogears",

  // ── Bayonetta ─────────────────────────────────────────────────────────────────
  "Bayonetta",
  "Bayonetta 2",
  "Bayonetta 3",
  "Bayonetta Origins: Cereza and the Lost Demon",

  // ── Super Smash Bros ──────────────────────────────────────────────────────────
  "Super Smash Bros",
  "Super Smash Bros Melee",
  "Super Smash Bros Brawl",
  "Super Smash Bros for Wii U",
  "Super Smash Bros for Nintendo 3DS",
  "Super Smash Bros Ultimate",

  // ── Autres Nintendo ───────────────────────────────────────────────────────────
  "Arms",
  "Ring Fit Adventure",
  "Nintendo Switch Sports",
  "Wii Sports",
  "Wii Sports Resort",
  "Wii Fit",
  "Wii Fit Plus",
  "Wii Party",
  "Nintendo Land",
  "1-2-Switch",
  "Nintendogs",
  "Brain Age",
  "Tomodachi Life",
  "Miitopia",
  "Luigi's Mansion",
  "Luigi's Mansion: Dark Moon",
  "Luigi's Mansion 3",
  "Golden Sun",
  "Golden Sun: The Lost Age",
  "Golden Sun: Dark Dawn",
  "Advance Wars",
  "Advance Wars 2: Black Hole Rising",
  "Astral Chain",

  // ── PC Online / Battle Royale ─────────────────────────────────────────────────
  "Minecraft",
  "Minecraft: Dungeons",
  "Minecraft: Story Mode",
  "Minecraft Legends",
  "Fortnite",
  "Apex Legends",
  "Valorant",
  "League of Legends",
  "Dota 2",
  "Among Us",
  "Fall Guys",
  "Rocket League",
  "Phasmophobia",
  "Lethal Company",
  "Palworld",
  "Valheim",
  "Rust",
  "ARK: Survival Evolved",
  "ARK: Survival Ascended",
  "Terraria",
  "Stardew Valley",
  "No Man's Sky",
  "Subnautica",
  "Subnautica: Below Zero",
  "Grounded",
  "Astroneer",
  "The Forest",
  "Sons of the Forest",

  // ── Counter-Strike / Valve ────────────────────────────────────────────────────
  "Counter-Strike 1.6",
  "Counter-Strike: Source",
  "Counter-Strike: Global Offensive",
  "Counter-Strike 2",
  "Half-Life",
  "Half-Life 2",
  "Half-Life: Alyx",
  "Portal",
  "Portal 2",
  "Left 4 Dead",
  "Left 4 Dead 2",
  "Team Fortress 2",
  "Dota 2",
  "Garry's Mod",
  "Artifact",

  // ── Overwatch / Blizzard ──────────────────────────────────────────────────────
  "Overwatch",
  "Overwatch 2",
  "Diablo",
  "Diablo II",
  "Diablo III",
  "Diablo IV",
  "Diablo: Immortal",
  "StarCraft",
  "StarCraft: Brood War",
  "StarCraft II: Wings of Liberty",
  "StarCraft II: Heart of the Swarm",
  "StarCraft II: Legacy of the Void",
  "Warcraft",
  "Warcraft II",
  "Warcraft III: Reign of Chaos",
  "Warcraft III: Reforged",
  "World of Warcraft",
  "World of Warcraft: The Burning Crusade",
  "World of Warcraft: Wrath of the Lich King",
  "World of Warcraft: Cataclysm",
  "World of Warcraft: Dragonflight",
  "Hearthstone",
  "Heroes of the Storm",

  // ── Doom / id Software ────────────────────────────────────────────────────────
  "Doom",
  "Doom II",
  "Doom 3",
  "Doom (2016)",
  "Doom Eternal",
  "Quake",
  "Quake II",
  "Quake III Arena",
  "Quake Live",
  "Unreal Tournament",
  "Unreal Tournament 2004",
  "Wolfenstein 3D",
  "Wolfenstein: The New Order",
  "Wolfenstein II: The New Colossus",
  "Rage",
  "Rage 2",

  // ── Battlefield ───────────────────────────────────────────────────────────────
  "Battlefield 1942",
  "Battlefield Vietnam",
  "Battlefield 2",
  "Battlefield 2142",
  "Battlefield: Bad Company",
  "Battlefield: Bad Company 2",
  "Battlefield 3",
  "Battlefield 4",
  "Battlefield Hardline",
  "Battlefield 1",
  "Battlefield V",
  "Battlefield 2042",

  // ── Gran Turismo / Racing ─────────────────────────────────────────────────────
  "Gran Turismo",
  "Gran Turismo 2",
  "Gran Turismo 3: A-Spec",
  "Gran Turismo 4",
  "Gran Turismo 5",
  "Gran Turismo 6",
  "Gran Turismo Sport",
  "Gran Turismo 7",
  "Forza Motorsport",
  "Forza Motorsport 4",
  "Forza Motorsport 5",
  "Forza Motorsport 7",
  "Forza Motorsport (2023)",
  "Forza Horizon",
  "Forza Horizon 2",
  "Forza Horizon 3",
  "Forza Horizon 4",
  "Forza Horizon 5",
  "Need for Speed: Underground",
  "Need for Speed: Underground 2",
  "Need for Speed: Most Wanted",
  "Need for Speed: Carbon",
  "Need for Speed: Hot Pursuit",
  "Need for Speed: The Run",
  "Need for Speed: Rivals",
  "Need for Speed: Payback",
  "Need for Speed Heat",
  "Need for Speed Unbound",
  "Burnout 3: Takedown",
  "Burnout Paradise",
  "Burnout Revenge",
  "Ridge Racer",
  "Ridge Racer Type 4",
  "Daytona USA",
  "OutRun 2",
  "Wreckfest",
  "Hot Wheels Unleashed",
  "Grid",
  "DiRT Rally 2.0",

  // ── Persona / SMT ─────────────────────────────────────────────────────────────
  "Persona 3",
  "Persona 3 FES",
  "Persona 3 Portable",
  "Persona 3 Reload",
  "Persona 4",
  "Persona 4 Golden",
  "Persona 5",
  "Persona 5 Royal",
  "Persona 5 Strikers",
  "Persona 5 Tactica",
  "Persona 4 Arena",
  "Persona Q",
  "Shin Megami Tensei III: Nocturne",
  "Shin Megami Tensei IV",
  "Shin Megami Tensei V",
  "Catherine",
  "Catherine: Full Body",

  // ── Tales of ──────────────────────────────────────────────────────────────────
  "Tales of Symphonia",
  "Tales of the Abyss",
  "Tales of Vesperia",
  "Tales of Graces",
  "Tales of Xillia",
  "Tales of Xillia 2",
  "Tales of Zestiria",
  "Tales of Berseria",
  "Tales of Arise",
  "Tales of Kizna Armonics",

  // ── Ni no Kuni / Square RPG ───────────────────────────────────────────────────
  "Ni no Kuni: Wrath of the White Witch",
  "Ni no Kuni 2: Revenant Kingdom",
  "Chrono Trigger",
  "Chrono Cross",
  "EarthBound",
  "Mother 3",
  "Kingdom Hearts",
  "Kingdom Hearts 2",
  "Kingdom Hearts 3",
  "Kingdom Hearts: Chain of Memories",
  "Kingdom Hearts: Birth by Sleep",

  // ── Baldur's Gate / CRPG ─────────────────────────────────────────────────────
  "Baldur's Gate",
  "Baldur's Gate 2",
  "Baldur's Gate 3",
  "Pillars of Eternity",
  "Pillars of Eternity 2",
  "Divinity: Original Sin",
  "Divinity: Original Sin 2",
  "Planescape: Torment",
  "Neverwinter Nights",
  "Dragon's Dogma",
  "Dragon's Dogma 2",
  "The Outer Worlds",
  "Wasteland 3",
  "Pathfinder: Wrath of the Righteous",

  // ── Silent Hill ───────────────────────────────────────────────────────────────
  "Silent Hill",
  "Silent Hill 2",
  "Silent Hill 3",
  "Silent Hill 4: The Room",
  "Silent Hill: Homecoming",
  "Silent Hill: Downpour",
  "Silent Hill 2 Remake",
  "Silent Hill f",

  // ── Dead Space / Horror ───────────────────────────────────────────────────────
  "Dead Space",
  "Dead Space 2",
  "Dead Space 3",
  "Dead Space Remake",
  "The Evil Within",
  "The Evil Within 2",
  "Alan Wake",
  "Alan Wake 2",
  "Outlast",
  "Outlast 2",
  "Amnesia: The Dark Descent",
  "Amnesia: Rebirth",
  "Five Nights at Freddy's",
  "Alien: Isolation",
  "Prey (2017)",
  "Control",
  "Soma",

  // ── Prince of Persia / Devil May Cry ─────────────────────────────────────────
  "Prince of Persia",
  "Prince of Persia: The Sands of Time",
  "Prince of Persia: Warrior Within",
  "Prince of Persia: The Two Thrones",
  "Prince of Persia (2008)",
  "Devil May Cry",
  "Devil May Cry 2",
  "Devil May Cry 3: Dante's Awakening",
  "Devil May Cry 4",
  "Devil May Cry 5",
  "DmC: Devil May Cry",

  // ── FromSoft / Action RPG ─────────────────────────────────────────────────────
  "Nioh",
  "Nioh 2",
  "Code Vein",
  "Lies of P",
  "Lords of the Fallen",
  "Stranger of Paradise: Final Fantasy Origin",

  // ── PlayStation Exclusives ────────────────────────────────────────────────────
  "Horizon Zero Dawn",
  "Horizon Forbidden West",
  "Ghost of Tsushima",
  "Days Gone",
  "Returnal",
  "Ratchet & Clank",
  "Ratchet & Clank: Going Commando",
  "Ratchet & Clank: Up Your Arsenal",
  "Ratchet & Clank: Tools of Destruction",
  "Ratchet & Clank (2016)",
  "Ratchet & Clank: Rift Apart",
  "inFamous",
  "inFamous 2",
  "inFamous Second Son",
  "Detroit: Become Human",
  "Until Dawn",
  "Knack",
  "Knack 2",
  "Killzone 2",
  "Killzone 3",
  "Killzone Shadow Fall",
  "Resistance: Fall of Man",
  "Resistance 2",
  "Resistance 3",
  "The Order: 1886",
  "MediEvil",
  "MediEvil (2019)",
  "Astro's Playroom",
  "Astro Bot",
  "Sly Cooper and the Thievius Raccoonus",
  "Sly 2: Band of Thieves",
  "Sly 3: Honor Among Thieves",
  "Jak and Daxter: The Precursor Legacy",
  "Jak II",
  "Jak 3",
  "Daxter",
  "LocoRoco",
  "Patapon",
  "Patapon 2",
  "Death Stranding",
  "Death Stranding: Director's Cut",

  // ── Xbox Exclusives ───────────────────────────────────────────────────────────
  "Gears of War",
  "Gears of War 2",
  "Gears of War 3",
  "Gears of War: Judgment",
  "Gears 4",
  "Gears 5",
  "Fable",
  "Fable II",
  "Fable III",
  "Crackdown",
  "Crackdown 2",
  "Crackdown 3",
  "Banjo-Kazooie",
  "Banjo-Tooie",
  "Banjo-Kazooie: Nuts & Bolts",
  "Perfect Dark",
  "Perfect Dark Zero",
  "GoldenEye 007",
  "Conker's Bad Fur Day",
  "Conker: Live & Reloaded",
  "Jade Empire",
  "Blue Dragon",
  "Lost Odyssey",
  "Titanfall",
  "Titanfall 2",
  "Sea of Thieves",
  "Grounded",
  "Hi-Fi Rush",
  "Forza (all)",
  "State of Decay",
  "State of Decay 2",

  // ── Sega ──────────────────────────────────────────────────────────────────────
  "Jet Set Radio",
  "Jet Set Radio Future",
  "Crazy Taxi",
  "Crazy Taxi 2",
  "Virtua Fighter",
  "Virtua Fighter 5",
  "Virtua Cop",
  "Streets of Rage",
  "Streets of Rage 2",
  "Streets of Rage 3",
  "Streets of Rage 4",
  "Golden Axe",
  "Golden Axe II",
  "Shinobi",
  "Altered Beast",
  "Phantasy Star Online",
  "Phantasy Star Online 2",
  "Yakuza 0",
  "Yakuza Kiwami",
  "Yakuza Kiwami 2",
  "Yakuza 6: The Song of Life",
  "Yakuza: Like a Dragon",
  "Like a Dragon: Ishin!",
  "Like a Dragon: Infinite Wealth",
  "Judgment",
  "Lost Judgment",
  "Valkyria Chronicles",
  "Valkyria Chronicles 4",
  "Panzer Dragoon",
  "Panzer Dragoon Orta",
  "NiGHTS into Dreams",
  "NiGHTS: Journey of Dreams",
  "Shenmue",
  "Shenmue II",
  "Shenmue III",
  "Space Channel 5",
  "Virtua Tennis",
  "Sega Rally Championship",
  "Super Monkey Ball",
  "Super Monkey Ball: Banana Mania",
  "Total War: Shogun 2",
  "Total War: Three Kingdoms",
  "Total War: Warhammer",
  "Total War: Warhammer II",

  // ── Square Enix divers ────────────────────────────────────────────────────────
  "Nier: Automata",
  "Nier Replicant",
  "Drakengard",
  "Drakengard 3",
  "SteamWorld Dig 2",
  "Octopath Traveler",
  "Octopath Traveler 2",
  "Bravely Default",
  "Bravely Default 2",
  "Dragon Quest Treasures",
  "Star Ocean: The Second Story",
  "Star Ocean: The Divine Force",

  // ── Capcom divers ─────────────────────────────────────────────────────────────
  "Okami",
  "Okami HD",
  "Viewtiful Joe",
  "Viewtiful Joe 2",
  "Ace Attorney",
  "Phoenix Wright: Ace Attorney",
  "Phoenix Wright: Ace Attorney Trilogy",
  "Ace Attorney: Apollo Justice",
  "Dragon's Dogma: Dark Arisen",

  // ── Konami divers ─────────────────────────────────────────────────────────────
  "Frogger",
  "Dance Dance Revolution",
  "Dance Dance Revolution SuperNOVA",
  "Pro Evolution Soccer",
  "Contra",
  "Contra III",
  "Gradius",
  "Gradius V",
  "Bomberman",
  "Bomberman 64",
  "Super Bomberman R",
  "Silent Hill P.T.",

  // ── Namco Bandai ──────────────────────────────────────────────────────────────
  "Pac-Man",
  "Ms. Pac-Man",
  "Pac-Man Championship Edition 2",
  "Galaga",
  "Dig Dug",
  "Dragon Ball Z: Budokai",
  "Dragon Ball Z: Budokai Tenkaichi 3",
  "Dragon Ball FighterZ",
  "Dragon Ball Xenoverse",
  "Dragon Ball Xenoverse 2",
  "Soul Calibur",
  "Soul Calibur 2",
  "Soul Calibur 6",
  "Ace Combat 7: Skies Unknown",
  "Ridge Racer (Namco)",
  "One Piece: Pirate Warriors 4",
  "Naruto: Ultimate Ninja Storm 4",

  // ── Activision Blizzard ───────────────────────────────────────────────────────
  "Guitar Hero",
  "Guitar Hero II",
  "Guitar Hero III: Legends of Rock",
  "Guitar Hero: World Tour",
  "Guitar Hero 5",
  "Rock Band",
  "Rock Band 2",
  "Rock Band 3",
  "Rock Band 4",
  "Tony Hawk's Pro Skater",
  "Tony Hawk's Pro Skater 2",
  "Tony Hawk's Pro Skater 3",
  "Tony Hawk's Pro Skater 4",
  "Tony Hawk's Pro Skater 1+2",
  "Tony Hawk's Underground",
  "Tony Hawk's Underground 2",
  "Spiderman (Activision)",
  "Prototype",
  "Prototype 2",
  "Skylanders: Spyro's Adventure",

  // ── Ubisoft ───────────────────────────────────────────────────────────────────
  "Rayman",
  "Rayman 2: The Great Escape",
  "Rayman 3: Hoodlum Havoc",
  "Rayman Origins",
  "Rayman Legends",
  "Watch Dogs",
  "Watch Dogs 2",
  "Watch Dogs: Legion",
  "Just Cause 2",
  "Just Cause 3",
  "Just Cause 4",
  "Far Cry",
  "Far Cry 2",
  "Far Cry 3",
  "Far Cry 4",
  "Far Cry 5",
  "Far Cry 6",
  "Far Cry Primal",
  "Far Cry New Dawn",
  "Tom Clancy's Rainbow Six Siege",
  "Tom Clancy's Ghost Recon: Wildlands",
  "Tom Clancy's Ghost Recon: Breakpoint",
  "Tom Clancy's The Division",
  "Tom Clancy's The Division 2",
  "Scott Pilgrim vs. the World: The Game",
  "Anno 1800",
  "Anno 2070",

  // ── Rockstar / 2K ─────────────────────────────────────────────────────────────
  "Bully",
  "Bully: Scholarship Edition",
  "L.A. Noire",
  "Midnight Club",
  "Midnight Club II",
  "Midnight Club: Los Angeles",
  "Sleeping Dogs",
  "Mafia",
  "Mafia 2",
  "Mafia 3",
  "Mafia: Definitive Edition",
  "XCOM: Enemy Unknown",
  "XCOM 2",
  "XCOM: Chimera Squad",
  "Civilization Beyond Earth",

  // ── Bethesda / ZeniMax ────────────────────────────────────────────────────────
  "Dishonored",
  "Dishonored 2",
  "Dishonored: Death of the Outsider",
  "Prey (2006)",
  "Rage",
  "The Evil Within (id/Bethesda)",
  "Quake Champions",

  // ── Troisième place indé ──────────────────────────────────────────────────────
  "Hollow Knight",
  "Hollow Knight: Silksong",
  "Shovel Knight",
  "Ori and the Blind Forest",
  "Ori and the Will of the Wisps",
  "Cuphead",
  "Celeste",
  "Undertale",
  "Deltarune",
  "Axiom Verge",
  "Blasphemous",
  "Blasphemous 2",
  "Super Meat Boy",
  "Limbo",
  "Inside",
  "Little Big Planet",
  "Little Big Planet 2",
  "Little Big Planet 3",
  "Braid",
  "Fez",
  "FTL: Faster Than Light",
  "The Binding of Isaac",
  "The Binding of Isaac: Rebirth",
  "Risk of Rain 2",
  "Dead Cells",
  "Hades",
  "Hades II",
  "Rogue Legacy",
  "Rogue Legacy 2",
  "Slay the Spire",
  "Monster Train",
  "Balatro",

  // ── Narrative / Aventure ──────────────────────────────────────────────────────
  "Life is Strange",
  "Life is Strange: Before the Storm",
  "Life is Strange: True Colors",
  "A Plague Tale: Innocence",
  "A Plague Tale: Requiem",
  "Firewatch",
  "Oxenfree",
  "Oxenfree II",
  "Disco Elysium",
  "Gris",
  "Spiritfarer",
  "What Remains of Edith Finch",
  "Outer Wilds",
  "Journey",
  "Myst",
  "Riven",
  "Dear Esther",
  "Abzu",
  "The Stanley Parable",
  "Observation",
  "Tell Me Why",
  "Twelve Minutes",
  "Pentiment",

  // ── Musique / Rythme ──────────────────────────────────────────────────────────
  "Just Dance",
  "Just Dance 2023",
  "Rhythm Heaven",
  "Rhythm Heaven Megamix",
  "Hatsune Miku: Project DIVA",
  "Hatsune Miku: Project DIVA Mega Mix",
  "Beat Saber",
  "Crypt of the NecroDancer",
  "Cadence of Hyrule",
  "Friday Night Funkin'",

  // ── Sports extrêmes / skate ───────────────────────────────────────────────────
  "Skate",
  "Skate 2",
  "Skate 3",
  "Shaun White Snowboarding",
  "SSX",
  "SSX Tricky",
  "SSX On Tour",

  // ── Star Wars ─────────────────────────────────────────────────────────────────
  "Star Wars: Battlefront (2004)",
  "Star Wars: Battlefront II (2005)",
  "Star Wars: Battlefront (2015)",
  "Star Wars: Battlefront II (2017)",
  "Star Wars Jedi: Fallen Order",
  "Star Wars Jedi: Survivor",
  "Star Wars: Knights of the Old Republic",
  "Star Wars: Knights of the Old Republic II",
  "Lego Star Wars: The Video Game",
  "Lego Star Wars: The Complete Saga",
  "Lego Star Wars: The Skywalker Saga",
  "Star Wars: The Force Unleashed",
  "Star Wars: The Force Unleashed II",
  "Star Wars: Squadrons",
  "Star Wars: Episode 1 Racer",

  // ── Lego ──────────────────────────────────────────────────────────────────────
  "Lego Batman",
  "Lego Batman 2",
  "Lego Batman 3",
  "Lego Marvel Super Heroes",
  "Lego Marvel Super Heroes 2",
  "Lego Marvel's Avengers",
  "Lego Jurassic World",
  "Lego Dimensions",
  "Lego Indiana Jones",
  "Lego Harry Potter: Years 1-4",
  "Lego Harry Potter: Years 5-7",

  // ── Injustice / DC ────────────────────────────────────────────────────────────
  "Injustice: Gods Among Us",
  "Injustice 2",
  "Superman Returns",
  "Superman 64",
  "Batman Forever",

  // ── Fighting divers ───────────────────────────────────────────────────────────
  "King of Fighters '98",
  "King of Fighters 2002",
  "King of Fighters XIII",
  "King of Fighters XV",
  "King of Fighters XVI",
  "Guilty Gear Xrd",
  "Guilty Gear Strive",
  "BlazBlue: Calamity Trigger",
  "BlazBlue: Cross Tag Battle",
  "Dragon Ball Z: Budokai Tenkaichi 3",
  "Dragon Ball FighterZ",
  "Virtua Fighter 5: Ultimate Showdown",
  "Dead or Alive 5",
  "Dead or Alive 6",
  "Samurai Shodown",
  "The Last Blade",
  "Garou: Mark of the Wolves",
  "MultiVersus",

  // ── Classiques rétro ──────────────────────────────────────────────────────────
  "Space Invaders",
  "Asteroids",
  "Pong",
  "Centipede",
  "Breakout",
  "Tetris",
  "Tetris Effect",
  "Tetris 99",
  "Puyo Puyo Tetris",
  "Lumines",
  "Columns",
  "Bubble Bobble",
  "Dig Dug",
  "Galaga '88",
  "R-Type",
  "Gradius",
  "1942",
  "Ghosts 'n Goblins",
  "Ghouls 'n Ghosts",
  "Bionic Commando",
  "Double Dragon",
  "River City Ransom",
  "Battletoads",
  "Contra",
  "Super C",
  "Contra III: The Alien Wars",
  "Ducktales",
  "Chip 'n Dale Rescue Rangers",
  "TaleSpin",
  "Adventures in the Magic Kingdom",
  "ActRaiser",
  "Actraiser Renaissance",

  // ── Open-world / Sandbox ──────────────────────────────────────────────────────
  "Watch Dogs: Legion",
  "Saints Row",
  "Saints Row 2",
  "Saints Row III",
  "Saints Row IV",
  "Sleeping Dogs: Definitive Edition",
  "Cyberpunk 2077",
  "The Outer Worlds",

  // ── Stratégie temps réel ──────────────────────────────────────────────────────
  "Command & Conquer",
  "Command & Conquer: Red Alert",
  "Command & Conquer: Tiberian Sun",
  "Command & Conquer: Generals",
  "Command & Conquer 3: Tiberium Wars",
  "Company of Heroes",
  "Company of Heroes 2",
  "Tropico 4",
  "Tropico 5",
  "Tropico 6",
  "Planet Coaster",
  "Planet Zoo",
  "Two Point Hospital",
  "Two Point Campus",
  "Anno 1800",
  "Frostpunk",
  "They Are Billions",
  "Humankind",

  // ── Simulation ────────────────────────────────────────────────────────────────
  "Microsoft Flight Simulator",
  "Euro Truck Simulator 2",
  "American Truck Simulator",
  "Farming Simulator 22",
  "Train Simulator",
  "Space Engineers",
  "Kerbal Space Program",
  "Kerbal Space Program 2",
  "Planet Coaster 2",

  // ── Autres populaires ─────────────────────────────────────────────────────────
  "Destiny",
  "Destiny 2",
  "Sea of Thieves",
  "Deep Rock Galactic",
  "Rainbow Six Siege",
  "Paladins",
  "Warframe",
  "Path of Exile",
  "Path of Exile 2",
  "Genshin Impact",
  "Honkai: Star Rail",
  "Wuthering Waves",
  "Blue Archive",
  "Zenless Zone Zero",
  "Hololive Error",
  "Escape from Tarkov",
  "Hunt: Showdown",
  "Dayz",
  "PlayerUnknown's Battlegrounds",
  "H1Z1",
  "Realm Royale",
  "Hyper Scape",

];
